### ISSUE TITLE
[SpiderPool] Submit mining pool registration information

### ISSUE THREAD

**Issue by SpiderDigital** [exsat-network/configurations#1]
**Please provide the following information for synchronizer.**

Account: spider.sat
Name: SpiderPool
Mining Address (optional): 1BM1sAcrfV6d4zPKytzziu4McLQDsFC2Qc
Homepage url: https://www.spiderpool.com/
Logo url: https://spiderpool.s3.us-west-1.amazonaws.com/images/logo-icon.png
Introduction:  SpiderPool, founded in 2018, is a self-developed integrated mining pool with stable operation and solid technology. We are proven to have accumulated rich experience in ETH and BTC mining pool operation, in-depth technological research, strong development and a technical team with more than 11 years of industry experience. After more than six years of accumulated efforts, SpiderPool's ETH (POW) mining pool was ranked 3rd in the world and SpiderPool's current main business BTC mining pool is also among the top in the whole network.

**Comment by RobinHolmes** [comment]
Added to configuration information, Thank you for your support.
