### ISSUE TITLE
Antpool Submit mining pool registration information

### ISSUE THREAD

**Issue by Apolooops** [exsat-network/configurations#10]
**Please provide the following information for synchronizer.**

Account: antpool
Name: antpool
Reward Account: 0xcf0d018af065426c8f3add976b8e19a3c7714128
Mining Address (optional): ["39C7fxSzEACPjM78Z7xdPxhf7mKxJwvfMJ","37jKPSmbEGwgfacCr2nayn1wTaqMAbA94Z"]
Homepage url: https://www.antpool.com/home
Logo url: https://www.antpool.com/brandVi
Introduction:

**Comment by Wiggins369** [comment]
Added to configuration information, Thank you for your support.
