### ISSUE TITLE
[BigONE] Submit validator registration information

### ISSUE THREAD

**Issue by LanfordCai** [exsat-network/configurations#19]
**Please provide the following information for validator.**

Account: bigone.sat
Name: BigONE
Homepage url: https://big.one/
Logo url: https://b.peatio.com/logos/BigONE_b.svg
Introduction: BigONE is a pioneering cryptocurrency exchange with a long-standing reputation for excellence. The platform serves as an all-in-one solution for digital assets, offering powerful and user-friendly features such as trading, staking, and financial services. With millions of users globally, BigONE is committed to making cryptocurrency accessible worldwide. The exchange has been a key player in the blockchain revolution, notably as a top block producer in the EOS ecosystem. BigONE is dedicated to leading the future of digital finance by providing a secure, seamless, and comprehensive user experience.

**Comment by Wiggins369** [comment]
Added to configuration information, Thank you for your support.
