### ISSUE TITLE
[exSat] Submit mining pool registration information

### ISSUE THREAD

**Issue by alexmao-zealot** [exsat-network/configurations#2]
**Please provide the following information for synchronizer.**

Account: xsatsync.sat
Name: exSat Foundation
Reward Account: 
Mining Address (optional): 
Homepage url: https://exsat.network/app/
Logo url: https://github.com/user-attachments/assets/9e55dc32-0d96-4869-9063-963cf64d5441
Introduction: exSat is a Layer 1.5 scaling solution designed to unlock the full potential of the Bitcoin ecosystem.

**Comment by Wiggins369** [comment]
Added
