### ISSUE TITLE
[mipool.sat] Submit validator registration information

### ISSUE THREAD

**Issue by mipool-one** [exsat-network/configurations#21]
**Please provide the following information for validator.**

Account: mipool.sat
Name: miPool
Homepage url: https://mipool.one/
Logo url: https://github.com/user-attachments/assets/4158e629-d162-4dfc-b25b-42a2b60476f4

Introduction: miPool is a professional cryptocurrency mining team that was established in 2016 and has been mining major cryptocurrencies and developing blockchain infrastructure technology, mainly in Asia. We have accumulated a lot of experience and know-how in Bitcoin POW and ETH POW mining, POS staking such as EOS DPoS and Polkadot NPoS, and Filecoin (WindowPoS) mining.

**Comment by Wiggins369** [comment]
Added to configuration information, Thank you for your support.
