### ISSUE TITLE
[treis.sat] Submit validator registration information

### ISSUE THREAD

**Issue by eosusa** [exsat-network/configurations#24]
**Please provide the following information for validator.**

Account: treis.sat
Name: Treis Blockchain
Homepage url: 
Logo url: https://eosusa.io/img/treis.png
Introduction: Founded in 2017 and headquartered in Greenville, South Carolina, USA, Treis Blockchain is a blockchain service provider specializing in the operations and management of immersion and hydro cooled mining operations. They also manage 100s of proof of stake validation nodes and provide consulting/development services for Web3 integrated solutions.

**Comment by Wiggins369** [comment]
Added to configuration information, Thank you for your support.
