### ISSUE TITLE
[inf.sat] Submit validator registration information

### ISSUE THREAD

**Issue by alex-infstones** [exsat-network/configurations#30]
**Please provide the following information for validator.**

Account: inf.sat
Name: InfStones
Homepage url: https://infstones.com/
Logo url: https://raw.githubusercontent.com/github-infstones/eigenlayer/main/logo_black.png
Introduction: InfStones is committed to supporting a wide range of AVSes and reward delegators through our Giveaway! Learn more: https://infstones.com/

**Comment by Wiggins369** [comment]
Added to configuration information, Thank you for your support.
