### ISSUE TITLE
[cactus.sat] Submit validator registration information

### ISSUE THREAD

**Issue by YuWT-CN** [exsat-network/configurations#32]
**Please provide the following information for validator.**

Account: cactus.sat
Name: myCactus
Homepage url: https://www.mycactus.com/
Logo url: https://custody-publicresource.s3.ap-southeast-1.amazonaws.com/icon/Cactus.png
Introduction: Leading Qualified Custodian for Digital Assets.

**Comment by Wiggins369** [comment]
Added to configuration information, Thank you for your support.
