### ISSUE TITLE
[F2Pool] Submit mining pool registration information

### ISSUE THREAD

**Issue by f2pool-monitor** [exsat-network/configurations#35]
**Please provide the following information for synchronizer.**

Account: f2pool.sat
Name: F2Pool
Reward Account: 0x167cD253BC5B35641d17e10615B5f7Da146E39d5
Mining Address (optional): 1KGG9kvV5zXiqyQAMfY32sGt9eFLMmgpgX
Homepage url: https://f2pool.com
Logo url: https://static.f2pool.com/static/images/logo.png
Introduction: world’s leading mining pool.

**Comment by pursonc** [comment]
Already added

**Comment by andymiler2024** [comment]
Done.
