### ISSUE TITLE
[MaxiPool] Submit mining pool registration information

### ISSUE THREAD

**Issue by edwardlv** [exsat-network/configurations#36]
**Please provide the following information for synchronizer.**

Account: maxipool.sat
Name: MaxiPool
Reward Account: 0x061A9a3F93Cc5891BA1898e7F1cd436af76092C2
Mining Address (optional): 36r3YqAXWpyqNcczjCBdHrYZ3m8X56WDzx
Homepage url: https://maxipool.org/
Logo url: https://maxipool.s3.ap-southeast-1.amazonaws.com/Maxipool.svg
Introduction: MaxiPool, the best bitcoin&fractal bitcoin merge mining pool

**Comment by pursonc** [comment]
added

**Comment by andymiler2024** [comment]
Done.
