### ISSUE TITLE
[Antpool] Submit mining pool registration information 

### ISSUE THREAD

**Issue by AntPoolDev** [exsat-network/configurations#37]
**Please provide the following information for synchronizer.**

Account: antpoole.sat
Name: Antpool
Reward Account: 0x0Bd3Df983e80048C6A2e388FC173436c55c0190b
Mining Address (optional): "39C7fxSzEACPjM78Z7xdPxhf7mKxJwvfMJ","37jKPSmbEGwgfacCr2nayn1wTaqMAbA94Z"
Homepage url: https://www.antpool.com/home
Logo url: https://imgur.com/Ne6YPp2
Introduction: The world's leading cryptocurrency mining platform.

**Comment by pursonc** [comment]
Added.

**Comment by andymiler2024** [comment]
Done.
