### ISSUE TITLE
[ViaBTC] Submit mining pool registration information

### ISSUE THREAD

**Issue by zaneYang20240619** [exsat-network/configurations#39]
Account: viabtc21.sat
Name: ViaBTC
Reward Account: 0x6a931D9DE30a5f313A566775a135CF47D40c0ccD
Mining Address: "1PuJjnF476W3zXfVYmJfGnouzFDAXakkL4", "18cBEMRxXHqzWWCxZNtU91F5sbUNKhL5PX"
Homepage url: https://www.viabtc.com/
Logo url: https://www.viabtc.com/images/header/hd_logo.png
Introduction: A Global Cryptocurrency Mining Pool

**Comment by pursonc** [comment]
Added.

**Comment by andymiler2024** [comment]
Done.
