### ISSUE TITLE
[ViaBTC] Submit mining pool registration information

### ISSUE THREAD

**Issue by polar-li** [exsat-network/configurations#41]
**Please provide the following information for synchronizer.**

Account: viabtc1.sat
Name: ViaBTC
Reward Account: 0x46344A671e9Bf425db2d11F1e44FD12A51d52524
Mining Address (optional): mq8mJR5A15VusVfBq5AEpZjhKS1D34M3vi
Homepage url: https://www.viabtc.com/
Logo url: https://www.viabtc.com/images/header/hd_logo.png
Introduction: A Global Cryptocurrency Mining Pool

On the test3 test network.

**Comment by pursonc** [comment]
Added

**Comment by andymiler2024** [comment]
Done.
