### ISSUE TITLE
[aa] Submit validator registration information

### ISSUE THREAD

**Issue by xwc1125** [exsat-network/configurations#42]
faa

**Comment by andymiler2024** [comment]
Below is a template for the issue submission, using sample data:

Issue Title:[Validator's Name]Submit validator registration information

Content:
Please provide the following information for Validator.

Registration info:
*Account: coolvali.sat

Display info in Frontend:
*Name: coolvali
*Logo url: https://cool.network/img/logo.png
Homepage url: https://coolval.com
Introduction: A cool...
