### ISSUE TITLE
[C² Ventures] Submit validator registration information

### ISSUE THREAD

**Issue by songgeng87** [exsat-network/configurations#46]
**Please provide the following information for validator.**

Account: c2sat.sat
Name: C² Ventures
Homepage url: https://www.csquared.vc/
Logo url: https://static.wixstatic.com/media/368df4_96febeaa9c314af99972fdf7869f7f41~mv2.png  
Introduction: 

C² Ventures takes a chain-agnostic approach, making early-stage investments across all major layer 1 and layer 2 ecosystems.

We focus on empowering builders with the capital and operational expertise to build and scale the next generation of Web3 and Metaverse applications.

**Comment by andymiler2024** [comment]
Done.
