### ISSUE TITLE
[Greymass] Submit validator registration information

### ISSUE THREAD

**Issue by unstoppableash** [exsat-network/configurations#47]
**Please provide the following information for validator.**

Account: greymass.sat
Name: Greymass
Homepage url: https://www.greymass.com/
Logo url: https://www.greymass.com/greymass_logo_256X256.png
Introduction: We're Greymass, an imaginative team of developers and researchers who are paving the way to a better decentralized internet.

**Comment by andymiler2024** [comment]
Done.
