### ISSUE TITLE
[F2Pool] Submit validator registration information

### ISSUE THREAD

**Issue by f2pool-monitor** [exsat-network/configurations#48]
**Please provide the following information for validator.**

Account: f2poolvl.sat
Name: F2Pool
Homepage url: https://f2pool.com/
Logo url: https://static.f2pool.com/static/images/f2pool_logo.png
Introduction: f2pool is the world’s leading Bitcoin and crypto mining pool since 2013.

**Comment by andymiler2024** [comment]
Done.
