### ISSUE TITLE
[Laomao] Submit validator registration information

### ISSUE THREAD

**Issue by LMBlackMyth** [exsat-network/configurations#49]
**Please provide the following information for validator.**

Account: lm.sat
Name: Laomao
Homepage url: https://medium.com/@eoslaomao
Logo url: https://avatars.githubusercontent.com/u/38250257?s=200&v=4
Introduction: Laomao is a key node for the launch of the EOS network and performs the most critical operations for full-vote launch.

**Comment by andymiler2024** [comment]
Done.
