### ISSUE TITLE
[Everstake] Submit validator registration information

### ISSUE THREAD

**Issue by oarypovskyi-everstake** [exsat-network/configurations#5]
**Please provide the following information for validator.**

Account: everstk.sat
Name: Everstake
Homepage url: https://everstake.one/
Logo url: https://everstake.one/logo.png
Introduction: Everstake is a top-tier responsible validator trusted by 725k+ users across 75+ blockchain networks. Created by engineers for the entire community in 2018

**Comment by RobinHolmes** [comment]
Added to configuration information, Thank you for your support.
