### ISSUE TITLE
[pgix.sat] Submit validator registration information

### ISSUE THREAD

**Issue by BradyGarcia** [exsat-network/configurations#50]
**Please provide the following information for validator.**

Account: pgix.sat
Name: Pythagoras Investments
Homepage url: https://pythagoras.investments/
Logo url:  https://pbs.twimg.com/profile_images/1554877727601496064/_-yAlmvI_400x400.jpg
Introduction:  At Pythagoras, we are quantitative traders of cryptocurrencies.

**Comment by andymiler2024** [comment]
Done.
