### ISSUE TITLE
[okxexsat.sat] Submit validator registration information

### ISSUE THREAD

**Issue by TiahWeiJun** [exsat-network/configurations#52]
**Please provide the following information for validator.**

Account: okxexsat.sat
Name: OKX
Homepage url: https://www.okx.com/
Logo url: https://static.coinall.ltd/cdn/web3/oklinkadmin/picture/49eefd82-ad25-4a1b-9662-ddd63ce27e72.png
Introduction: OKX is an innovative cryptocurrency exchange with advanced financial services. We rely on blockchain technology to provide everything you need for wise trading and investment.

**Comment by andymiler2024** [comment]
Done.
