### ISSUE TITLE
[certik.sat] Submit validator registration information

### ISSUE THREAD

**Issue by yijun-liu-c** [exsat-network/configurations#54]
**Please provide the following information for validator.**

Account: certik.sat
Name: Certik
Homepage url: https://www.certik.com/
Logo url: 
![Vertical_Black on Transparent Background_CertiK Logo](https://github.com/user-attachments/assets/e8cfd3c4-ad8d-4b3b-8143-6bc5b5fc80fe)
Introduction: CertiK is the world's leading smart contract auditor. We provide full-cycle security solutions for enterprises, including auditing, security rating,Compliance&AML,investment and other security-related services, elevating the entire Web3 journey of our clients.

**Comment by andymiler2024** [comment]
validator's info is uploaded.
