### ISSUE TITLE
[neoexsat.sat] Submit validator registration information

### ISSUE THREAD

**Issue by wjcbaggio** [exsat-network/configurations#56]
**Please provide the following information for validator.**

Account: neoexsat.sat
Name: Neo
Homepage url: neo.org
Logo url: https://s2.coinmarketcap.com/static/img/coins/64x64/1376.png
Introduction: Neo is an open-source community driven blockchain platform.

**Comment by andymiler2024** [comment]
validator's info is uploaded.
