### ISSUE TITLE
[kclabs.sat] Submit validator registration information

### ISSUE THREAD

**Issue by JudithCetton** [exsat-network/configurations#57]
**Please provide the following information for validator.**

Account: kclabs.sat
Name:  KuCoin Labs 
Homepage url:  https://www.kucoin.com/land/kucoinlabs
Logo url:  https://github.com/user-attachments/assets/f7805a68-563f-42a4-aafc-14cd3fc62023
Introduction:  KuCoin Labs diversified and intensified investments at very early-stage of projects and helped more BUIDLers achieve sustainable growth and success in the decentralized world.

**Comment by andymiler2024** [comment]
validator's info is uploaded.
