### ISSUE TITLE
[matrixpt.sat] Submit validator registration information

### ISSUE THREAD

**Issue by Jono-mp** [exsat-network/configurations#59]
**Please provide the following information for validator.**

Account: matrixpt.sat
Name: Matrixport
Homepage url: https://www.matrixport.com/
Logo url: [
![Matrixport_Vertical_Reversed@3x](https://github.com/user-attachments/assets/1acf7254-eae2-4667-8d1f-61ca3e98ee5a)
](url)
Introduction: Matrixport is the world’s leading, and Asia’s largest all-in-one hub for crypto financial services, with the commission to building an entry-grade ecosystem for the crypto space, by providing every user with a personalized super account that integrates features including crypto assets trading, investment, loan, custody, RWA, and research.

**Comment by andymiler2024** [comment]
Done.
