### ISSUE TITLE
[hashkey.sat] Submit validator registration information

### ISSUE THREAD

**Issue by 2019jack** [exsat-network/configurations#61]
**Please provide the following information for validator.**

Account: hashkey.sat
Name: HashKey Cloud
Homepage url: https://www.hashkey.cloud/
Logo url: https://www.hashkey.cloud/logo.svg
Introduction: 
HashKey Cloud, a leading provider of global Web3 infrastructure and a core member of the HashKey Group, focuses on delivering professional, stable, and secure blockchain services to clients worldwide. Since 2018, we have been deeply committed to blockchain infrastructure technologies, with our node validation services covering over 80 mainstream public chains. 
We have upgraded our product line as Web3 transitions from foundational technology to application development. Our new product line includes restaking, BTC Node  Validation, Ethereum Layer2, and STO Infra. We aim to meet the diverse needs of our clients and provide top-notch services to the global market.

**Comment by 2019jack** [comment]
@here update Logo url: https://www.hashkey.cloud/logo.svg

**Comment by andymiler2024** [comment]
Done.
