### ISSUE TITLE
[F2Pool] Submit mining pool registration information

### ISSUE THREAD

**Issue by f2pool-monitor** [exsat-network/configurations#8]
**Please provide the following information for synchronizer.**

Account: f2pool.sat
Name: F2Pool
Reward Account: 0x8DE23504855b7Fd67919cBc22b4639aa824c1eFB
Mining Address (optional):
Homepage url: https://f2pool.com
Logo url: https://static.f2pool.com/static/images/logo.png
Introduction: world’s leading mining pool.

**Comment by Wiggins369** [comment]
Added to configuration information, Thank you for your support.
